// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMvyHv_jk7DhpZVEy1N6rRMn2JlOKxc8A',
    appId: '1:211815677080:web:868cf83001c8d77ba464ed',
    messagingSenderId: '211815677080',
    projectId: 'electrum-ahmad',
    authDomain: 'electrum-ahmad.firebaseapp.com',
    storageBucket: 'electrum-ahmad.firebasestorage.app',
    measurementId: 'G-0TPKFC7B1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZU_PCny2YfHe0btsiIL82P8B4gYxF-fk',
    appId: '1:211815677080:android:4c35f6c3ce28d099a464ed',
    messagingSenderId: '211815677080',
    projectId: 'electrum-ahmad',
    storageBucket: 'electrum-ahmad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkXqZ4MJgwByGC4DjDJhJoiLMmmC3bP44',
    appId: '1:211815677080:ios:00ff30ec53a58cb2a464ed',
    messagingSenderId: '211815677080',
    projectId: 'electrum-ahmad',
    storageBucket: 'electrum-ahmad.firebasestorage.app',
    iosBundleId: 'com.electrum.ahmad.electrumAhmad',
  );
}
